networks:
  custom-network:
    driver: bridge

services:
  selenium-hub:
    image: selenium/hub:4.13.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - custom-network

  chrome:
    image: selenium/node-chrome:4.13.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - custom-network

  tests:
    build: .
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - SELENIUM_URL=http://selenium-hub:4444/wd/hub
    networks:
      - custom-network
    volumes:
      - ./report:/report
