name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker build
      uses: docker/setup-buildx-action@v2

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Compose services
      run: |
        docker compose up --build -d
        docker compose ps

    - name: Run tests
      run: |
        docker compose run tests

    - name: Test reporter
      uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/*.ndjson"
    
    - name: Shutdown Docker Compose
      if: always()
      run: |
        docker compose down
